# Generated by Django 6.0.6 on 2026-06-08 17:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_periods', '0002_auditperiod_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Supervisor'), (2, 'Leader'), (3, 'Member')], default=3)),
                ('mandays', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('audit_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='audit_periods.auditperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
