# Generated by Django 6.0.6 on 2026-06-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_periods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditperiod',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
